### ISSUE TITLE
Logging enhancements and configuration

### ISSUE THREAD

**Issue by josjevv** [bulletind/moire#11]
Allow different loglevel types, Like
* Debug (signature checks, output validation from ffmpeg, etc)
* Info (requests)
* Warn (invalid signature)
* Error (failed thumbnail generation)) 

mange which loglevel onwards should be visible by configuration. Most logging frameworks support this out of the box, like python logging or java.util.logging.

**Comment by meson10** [comment]
Available in logging branch.
