### ISSUE TITLE
Allow named collections 

### ISSUE THREAD

**Issue by josjevv** [bulletind/moire#21]
in order to facilitate logical grouping of media, the consumers of moire should be able to specify a collection. This collection should be visible as a root folder in the s3 storage bucket. Given the following example:

Assuming we have avatars and logos to upload, we can have separate collections for these. On S3 it would look like this:
* logos
  *  logo1.gif
  * logo2.gif
* avatar
  * avatar1.jpg
  * etc

In case no collection is given, it should fallback to a default collection. Also, for more complaint related use cases, consumers can e.g. separate collections per tenant/organisation. In case the organisation demands to delete all media, it's as simple as deleting the specific collection.

**Comment by meson10** [comment]
What does this mean?

**Comment by madhums** [comment]
@meson10 I guess what he means to say is, we should be able to store in containers (pseudo folders). For example 

Instead of above 

```
/logos/logos1.gif
/logos/logos2.gif
/avatars/avatar.jpg
/avatars/avatar2.jpg
```

To be able to group logical entities into folders and put things in them instead of putting everything in one place.

Is this right? @josjevv

**Comment by meson10** [comment]
@madhums Ah okay, got it now. Thank you very much. :+1:

**Comment by madhums** [comment]
you are more than welcome :)

**Comment by josjevv** [comment]
Correct, editor did not take over my indenting, changed it to bullet list.
