### ISSUE TITLE
how to use this??

### ISSUE THREAD

**Issue by madhums** [bulletind/moire#23]
There is no documentation on how to use this. I don't understand what problem it solves. What is supported from this library?

**Comment by meson10** [comment]
:stuck_out_tongue_closed_eyes:

**Comment by madhums** [comment]
Well, that doesn't really answer my question. Is there any future for this?

**Comment by meson10** [comment]
Yes. Ruben and I are working on turning this into a hosted service as well.
So yeah, one more week and you will have a lot of documentation.

**Comment by josjevv** [comment]
I am writing some more documentation to at least be able to set this op properly, hang on I will try to finish that this week
