### ISSUE TITLE
Max-age: 0 causes reload for each and every image

### ISSUE THREAD

**Issue by rubenstolk** [bulletind/moire#34]
Let's set this to something else, this causes performance issues in `sc-mobile`. @josjevv. (See also: https://github.com/changer/sc-mobile/issues/120)

**Comment by josjevv** [comment]
Ok, did some testing about the response headers:

thumbnail (image not processed, redirected to placeholder image):
Cache-Control	 max-age=0, no-cache, no-store
Pragma no-cache

thumbnail (image processed, redirected to actual thumbnail):
no Cache-control/pragma set

This works as intended.

**Comment by rubenstolk** [comment]
@josjevv In my opinion should the actual resource (on S3) not have a `max-age: 0` header, because that image might be requested by the browser multiple times in one session.

To show the undesired behavior you can login to http://changer.testing.safetychanger.com/inspectionapp-worker/ with Safari and put this in the console:

```js
var ajax = document.body.appendChild(document.createElement('sc-ajax'));
ajax.uri = '/api/inspectionapp/1.0/templates/561cb284bdc6070a00e12892';
ajax.generateRequest();

setInterval(function () {
  var img = new Image();
  img.src = ajax.lastResponse.introduction.attachments[0].thumbnail_url;

  console.log(img.src);
}, 5000);
```

Then check your network tab and see that this is resulting in something we don't want (the image to be downloaded from the server over and over again.

**Comment by rubenstolk** [comment]
The generated url is only valid for some time anyways, so the actual signed url on S3 could have an infinite cache header, it will never change.

**Comment by josjevv** [comment]
ok, I thought moire was sending this header, but it's amazon S3. I will dive into that then.

**Comment by josjevv** [comment]
I just get 304 for subsequent calls, on S3 no max-age headers are set on items.  Did you disable caching in your dev toolbar of some kind?

**Comment by rubenstolk** [comment]
Did you test in Safari?

--
BR, Ruben Stolk
+919561050034  |  +31646118037




On Tue, Oct 20, 2015 at 6:41 AM -0700, "Jos van Velzen" <notifications@github.com> wrote:












I just get 304 for subsequent calls, on S3 no max-age headers are set on items.  Did you disable caching in your dev toolbar of some kind?

**Comment by rubenstolk** [comment]
max-age 0 is there and especially mobile browsers will take that seriously...

--
BR, Ruben Stolk
+919561050034  |  +31646118037




On Tue, Oct 20, 2015 at 6:41 AM -0700, "Jos van Velzen" <notifications@github.com> wrote:












I just get 304 for subsequent calls, on S3 no max-age headers are set on items.  Did you disable caching in your dev toolbar of some kind?

**Comment by josjevv** [comment]
conclusions so far:
* max-age 0 is not there unless when status = pending (intended). Statements mentioned before were incorrect
* when no headers present, safari does not cache 302 redirects during a session, e.g. chrome does
* expires header to match the aws signing key expiration date allows caching for safari (and others) in a proper way

potential new issue (currently investigating):
* signing keys from client to moire also expire, just like with aws.
* because most browsers cache images during the session (except for safari), this was not a problem
* if the moire key expires and client does not refresh the signed url in time, moire will invalidate the key when it expires

**Comment by josjevv** [comment]
new issue remains but is a byproduct of the current design using timebased access tokens. When asset state = ready, expires header is set corresponding with the signature expiry date for both thumbnails as the assets itself
